#
#
# Try to find the FTGL libraries
# Once done this will define
#
# OGLFT_FOUND          - system has ftgl
# OGLFT_INCLUDE_DIR    - path to FTGL/FTGL.h
# OGLFT_LIBRARY      - the library that must be included
#
#

IF (OGLFT_LIBRARY AND OGLFT_INCLUDE_DIR)
  SET(OGLFT_FOUND "YES")
ELSE (OGLFT_LIBRARY AND OGLFT_INCLUDE_DIR)
  FIND_PATH(OGLFT_INCLUDE_DIR oglft/OGLFT.h PATHS /usr/local/include /usr/include)
  FIND_LIBRARY(OGLFT_LIBRARY OGLFT PATHS /usr/local/lib /usr/lib)
  
  IF (OGLFT_INCLUDE_DIR AND OGLFT_LIBRARY)
    SET(OGLFT_FOUND "YES")
  ELSE (OGLFT_INCLUDE_DIR AND OGLFT_LIBRARY)
    SET(OGLFT_FOUND "NO")
  ENDIF (OGLFT_INCLUDE_DIR AND OGLFT_LIBRARY)
ENDIF (OGLFT_LIBRARY AND OGLFT_INCLUDE_DIR)

IF (OGLFT_FOUND)
  MESSAGE(STATUS "Found OGLFT libraries at ${OGLFT_LIBRARY} and includes at ${OGLFT_INCLUDE_DIR}")
ELSE (OGLFT_FOUND)
  IF (OGLFT_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find OGLFT libraries")
  ENDIF (OGLFT_FIND_REQUIRED)
ENDIF (OGLFT_FOUND)
